server:
  post: 8080
  # ssl 적용시
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: ssafy

spring:
  jpa:
    show_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: update
  # test db (h2)
  datasource:
    url: jdbc:h2:mem:backend;MODE=MYSQL
    username: ssafy
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  # ec2 의 mysql 로 db 전환
  #datasource:
  #  url: jdbc:mysql://i7b105.p.ssafy.io:3306/backend?serverTimezone=Asia/Seoul
  #  username: root
  #  password: ssafy7b105
  #  driver-class-name: com.mysql.cj.jdbc.Driver
  # 외부 앱 키 파일 설정
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    include: API-KEY

jwt:
  secret: dyAeHubOOc8KaOfYB6XEQoEj1QzRlVgtjNL8PYs1A1tymZvvqkcEU7L1imkKHeDa
  # 5 * 60 * 1000 = 5minute
  access-expiration: 300000
  # 15 * 24 * 60 * 60 * 1000 = 15days
  refresh-expiration: 1296000000

